server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: LOTTO-ENGINE-ROUTE
          uri: lb://lotto-engine
          predicates:
            - Path=/lottery/**,/result/**,/results/**
          filters:
            - AuthenticationFilter
        - id: LOTTO-ENGINE-swagger-ROUTE
          uri: lb://lotto-engine
          predicates:
            - Path=/lotto-engine/v3/api-docs
            - Method=GET
        - id: NUMBERS-GENERATOR-swagger-ROUTE
          uri: lb://numbers-generator
          predicates:
            - Path=/numbers-generator/v3/api-docs
            - Method=GET
        - id: AUTH-SERVICE-ROUTE
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: AUTH-SERVICE-swagger-ROUTE
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/v3/api-docs
            - Method=GET

#http://localhost:8080/swagger-ui.html
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
#      - url: /v3/api-docs
#        name: API Gateway Service
      - url: /lotto-engine/v3/api-docs
        name: Lotto Engine
      - url: /numbers-generator/v3/api-docs
        name: Numbers Generator
      - url: /auth-service/v3/api-docs
        name: Authentication Service
    disable-swagger-default-url: true
    path: /swagger

management:
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
