server:
  port: 0

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lotto
    username: root
    password: example
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

jwt:
  expiration:
    minutes: 10
    seconds: 60
    millis: 1000
    refreshOffset: 10

springdoc:
  swagger-ui:
    path: /auth-service/swagger-ui.html
  api-docs:
    path: /auth-service/v3/api-docs


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
