server:
  port: 0

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/lotto
    username: root
    password: example
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        temp:
        use_jdbc_metadata_defaults: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

email:
  sender:
    queue: email.service
    exchange: auth.exchange
    routing-key:
      registration: email.sender.registration

jwt:
  expiration:
    minutes: 6
    seconds: 60
    millis: 1000
    refreshOffset: 10

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /auth-service/swagger-ui.html
  api-docs:
    path: /auth-service/v3/api-docs
