server:
  port: 0

spring:
  application:
    name: lotto-engine
  data:
    mongodb:
      host: mongo
      port: 27017
      database: lotto
      username: admin
      password: admin
      auto-index-creation: true
  main:
    allow-bean-definition-overriding: true

lotto:
  number-generator:
    service:
      url: "http://numbers-generator"
  time:
    drawDayOfWeek: 5
    drawHour: 20
    drawMinute: 0
    resultsMinute: 1
    drawSecond: 0
    drawTime: "${lotto.time.drawHour}:${lotto.time.drawMinute}:${lotto.time.drawSecond}}"
  result-announcer:
    win-message-received: "Congratulations you have won, but already received reward."
    win-message-not-received: "Congratulations you have won, you can receive reward."
    lose-message: "Unfortunately you didn't won."
  result-checker:
    scheduler-cron: "${lotto.time.drawSecond} ${lotto.time.resultsMinute} ${lotto.time.drawHour} * * ${lotto.time.drawDayOfWeek}"

springdoc:
  swagger-ui:
    path: /lotto-engine/swagger-ui.html
  api-docs:
    path: /lotto-engine/v3/api-docs
