server:
  port: 0

spring:
  application:
    name: mail-service
  mail:
    host: EMAIL_HOST
    username: EMAIL_HOST_ADDRESS
    password: EMAIL_HOST_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true

queues:
  names:
    account-created-event: email.service

email:
  sender:
    address: ${EMAIL_HOST_ADDRESS}

management:
  endpoints:
    web:
      exposure:
        include: health, refresh
